class freeipa(
  Boolean $master             = false,
  Boolean $replica            = false,
  Boolean $client             = false,

  $principal                  = undef,
  $adminpw                    = undef,
  $dmpw                       = undef,
  $password                   = undef,
  String $domain              = undef,
  String $realm               = undef,
  String $server              = undef,
  Array $forwarders           = [],
  String $hostname            = $facts['fqdn'],

  $keytab                     = undef,
  $ntpserver                  = undef,
  $nisdomain                  = undef,
  $ca_cert_file               = undef,
  $ip                         = undef,
  $idstart                    = undef,
  $idmax                      = undef,
  $ext_ca_type                = undef,
  $ext_cert_file              = undef,
  $dirsrv_cert_file           = undef,
  $dirsrv_pin                 = undef,
  $dirsrv_cert_name           = undef,
  $http_cert_file             = undef,
  $http_pin                   = undef,
  $http_cert_name             = undef,
  $subject                    = undef,
  $ca_algorithm               = undef,
  $forward_policy             = undef,
  $reverse_zone               = undef,
  $zonemgr                    = undef,
  Array $options              = [],
  Boolean $setup_dns          = false,
  Boolean $no_host_dns        = false,
  Boolean $no_hbac_allow      = false,
  Boolean $external_ca        = false,
  Boolean $auto_forwarders    = false,
  Boolean $no_forwarders      = false,
  Boolean $no_reverse         = false,
  Boolean $auto_reverse       = false,
  Boolean $no_ntp             = true,
  Boolean $mkhomedir          = false,
  Boolean $force              = false,
  Boolean $no_ssh             = false,
  Boolean $no_sshd            = false,
  Boolean $fixed_primary      = false,
  Boolean $no_nisdomain       = false,
  Boolean $ssh_trust_dns      = false,
  Boolean $force_join         = false,
  Boolean $force_ntp          = false,
  Boolean $no_sudo            = false,
  Boolean $no_dns_sshfp       = false,
  Boolean $noac               = false,
  Boolean $request_cert       = false,
  Boolean $setup_ca           = false,
  Boolean $setup_kra          = false,
  Boolean $skip_conncheck     = false,
  Boolean $skip_schema_check  = false,
  Boolean $allow_zone_overlap = false,
  Boolean $upgrade            = false,
){

  if $master {
    class{freeipa::masterinstall:
      realm            => $realm,
      domain           => $domain,
      dmpw             => $dmpw,
      adminpw          => $adminpw,
      hostname         => $hostname,
      options          => $options,
      setup_dns        => $setup_dns,
      mkhomedir        => $mkhomedir,
      no_host_dns      => $no_host_dns,
      no_ntp           => $no_ntp,
      no_hbac_allow    => $no_hbac_allow,
      ssh_trust_dns    => $ssh_trust_dns,
      no_ssh           => $no_ssh,
      no_sshd          => $no_sshd,
      external_ca      => $external_ca,
      auto_forwarders  => $auto_forwarders,
      no_forwarders    => $no_forwarders,
      no_reverse       => $no_reverse,
      auto_reverse     => $auto_reverse,
      ip               => $ip,
      idstart          => $idstart,
      idmax            => $idmax,
      ext_ca_type      => $ext_ca_type,
      ext_cert_file    => $ext_cert_file,
      dirsrv_cert_file => $dirsrv_cert_file,
      dirsrv_pin       => $dirsrv_pin,
      dirsrv_cert_name => $dirsrv_cert_name,
      http_cert_file   => $http_cert_file,
      http_pin         => $http_pin,
      http_cert_name   => $http_cert_name,
      ca_cert_file     => $ca_cert_file,
      subject          => $subject,
      ca_algorithm     => $ca_algorithm,
      forward_policy   => $forward_policy,
      reverse_zone     => $reverse_zone,
      zonemgr          => $zonemgr,
      forwarders       => $forwarders,
    }
  }

  if $replica {
    class{freeipa::replicainstall:
      realm              => $realm,
      domain             => $domain,
      adminpw            => $adminpw,
      password           => $password,
      principal          => $principal,
      hostname           => $hostname,
      server             => $server,
      options            => $options,
      setup_dns          => $setup_dns,
      mkhomedir          => $mkhomedir,
      no_host_dns        => $no_host_dns,
      no_ntp             => $no_ntp,
      ssh_trust_dns      => $ssh_trust_dns,
      no_ssh             => $no_ssh,
      no_sshd            => $no_sshd,
      auto_forwarders    => $auto_forwarders,
      no_forwarders      => $no_forwarders,
      no_reverse         => $no_reverse,
      auto_reverse       => $auto_reverse,
      ip                 => $ip,
      dirsrv_cert_file   => $dirsrv_cert_file,
      dirsrv_pin         => $dirsrv_pin,
      dirsrv_cert_name   => $dirsrv_cert_name,
      http_cert_file     => $http_cert_file,
      http_pin           => $http_pin,
      http_cert_name     => $http_cert_name,
      forward_policy     => $forward_policy,
      reverse_zone       => $reverse_zone,
      forwarders         => $forwarders,
      setup_ca           => $setup_ca,
      setup_kra          => $setup_kra,
      skip_conncheck     => $skip_conncheck,
      skip_schema_check  => $skip_schema_check,
      allow_zone_overlap => $allow_zone_overlap,
      upgrade            => $upgrade,
    }
  }

  if $client {
    class{freeipa::clientinstall:
      domain        => $domain,
      realm         => $realm,
      principal     => $principal,
      password      => $password,
      hostname      => $hostname,
      server        => $server,
      keytab        => $keytab,
      ntpserver     => $ntpserver,
      nisdomain     => $nisdomain,
      ca_cert_file  => $ca_cert_file,
      ip            => $ip,
      options       => $options,
      no_ntp        => $no_ntp,
      mkhomedir     => $mkhomedir,
      force         => $force,
      no_ssh        => $no_ssh,
      no_sshd       => $no_sshd,
      fixed_primary => $fixed_primary,
      no_nisdomain  => $no_nisdomain,
      ssh_trust_dns => $ssh_trust_dns,
      force_join    => $force_join,
      force_ntp     => $force_ntp,
      no_sudo       => $no_sudo,
      no_dns_sshfp  => $no_dns_sshfp,
      noac          => $noac,
      request_cert  => $request_cert,
      no_sssd       => $no_sssd,
    }
  }

}
